
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'locale/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '*.spec'

Layout/LineLength:
  Max: 190

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
    Max: 400

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'db/seeds.d/*'

Naming/MethodName:
  Exclude:
    - 'app/models/concerns/orchestration/*.rb'

Rails:
  Enabled: True

Rails/Date:
  Exclude:
    - 'foreman_snapshot_management.gemspec'

Rails/FindEach:
  Exclude:
    - 'app/models/foreman_snapshot_management/vmware_extensions.rb'

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
  SupportedStyles:
    - ruby19
    - hash_rockets

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - '*.gemspec'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

