
inherit_gem:
  theforeman-rubocop:
    #- lenient.yml
    #- default.yml
    - strict.yml

Layout/LineLength:
  Max: 190

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'test/**/*.rb'

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
    Max: 400

Metrics/PerceivedComplexity:
  Max: 10

Rails/Date:
  Exclude:
    - 'foreman_snapshot_management.gemspec'

Rails/FindEach:
  Exclude:
    - 'app/models/foreman_snapshot_management/vmware_extensions.rb'

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: template

Style/GuardClause:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - '*.gemspec'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

