language: ruby
install:
  - unset BUNDLE_GEMFILE
  - cd ..
  - git clone https://github.com/theforeman/foreman.git -b ${FOREMAN_CORE_BRANCH} --depth 1
  - cd foreman
  - echo "gemspec :path => '../foreman_snapshot_management'" > bundler.d/foreman_snapshot_management.local.rb
  - echo "gem 'foreman_fog_proxmox' $FOREMAN_FOG_PROXMOX" > bundler.d/foreman_fog_proxmox.local.rb
  - ln -s settings.yaml.test config/settings.yaml
  - ln -s database.yml.example config/database.yml
  - bundle install --jobs=3 --retry=3 --without journald development postgresql mysql2 console
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - bundle exec rubocop ../foreman_snapshot_management
  - bundle exec rake test:foreman_snapshot_management
  - bundle exec rake test TEST="test/unit/foreman/access_permissions_test.rb"
env:
  global:
    - TESTOPTS=-v
matrix:
  include:
    - rvm: 2.5
      env: FOREMAN_CORE_BRANCH=1.22-stable FOREMAN_FOG_PROXMOX_VERSION=0.10.2
    - rvm: 2.5
      env: FOREMAN_CORE_BRANCH=1.23-stable FOREMAN_FOG_PROXMOX_VERSION=0.10.2
    - rvm: 2.5
      env: FOREMAN_CORE_BRANCH=1.24-stable FOREMAN_FOG_PROXMOX_VERSION=0.10.2

addons:
  apt:
    packages:
    - nodejs
    - git
    - libsqlite3-dev
    - zlib1g-dev
    - libvirt-dev
