export const GET_SNAPSHOT_CREATE_REQUEST = 'GET_SNAPSHOT_CREATE_REQUEST';
export const GET_SNAPSHOT_CREATE_SUCCESS = 'GET_SNAPSHOT_CREATE_SUCCESS';
export const GET_SNAPSHOT_CREATE_FAILURE = 'GET_SNAPSHOT_CREATE_FAILURE';

export const SNAPSHOT_CREATE_URL = '/api/hosts/:hostId/snapshots';
