---
name: React Testing

on:
  pull_request:
    paths:
      - 'webpack/**'
      - 'package.json'
      - '.github/workflows/react.yml'
      - '*.js'
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12]
        foreman-core-branch: ['develop', '2.5-stable', '2.4-stable']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          ref: ${{ matrix.foreman-core-branch }}
          path: foreman

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm install
          cd foreman; npm install; cd -
        
      - name: Lint Stylesheets
        run: npm run stylelint
      - name: Lint Javascript
        run: npm run lint
      - name: Test
        run: npm run test
...
