---
name: React Testing

on:
  pull_request:
    paths:
      - 'webpack/**'
      - 'package.json'
      - '.github/workflows/react.yml'
      - '*.js'
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14]
        foreman-core-branch: ['develop', '3.9-stable', '3.8-stable']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          ref: ${{ matrix.foreman-core-branch }}
          path: foreman

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm install
          cd foreman; npm install; cd -

      - name: Lint Stylesheets
        run: npm run stylelint
      - name: Lint Javascript
        run: npm run lint
      - name: Test
        if: ${{ matrix.foreman-core-branch == 'develop' }}
        run: npm run test
        # skip SnapshotManagementCard-test, because the snapshot may differ depending on foreman-version
      - name: Test release
        if: ${{ matrix.foreman-core-branch != 'develop' }}
        run: npm run test:compat
...
