---
name: Release

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v*'
jobs:
  release:
    name: Release gem
    runs-on: ubuntu-latest
    environment: release
    if: github.repository_owner == 'ATIX-AG'

    permissions:
      id-token: write

    steps:
      - uses: voxpupuli/ruby-release@v0
