---
name: Ruby Tests
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rubocop:
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0

  test:
    name: Ruby
    strategy:
      fail-fast: false
      matrix:
        foreman:
          - develop
          - 3.12-stable
          - 3.11-stable
    needs: rubocop
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_snapshot_management
      matrix_exclude: '[{"ruby": "3.0", "node": "14"}]'
      foreman_version: ${{ matrix.foreman }}
